### ISSUE TITLE
Some recently added keywords are not highlighted

### ISSUE THREAD

**Issue by karel-brinda** [ibab/vim-snakemake#1]
Some recently added keywords are not highlighted, e.g.,:
* `conda:`
* `script:`

Unfortunately, the [official grammar specification](http://snakemake.readthedocs.io/en/stable/snakefiles/writing_snakefiles.html?highlight=grammar) is [not up-to-date](https://bitbucket.org/snakemake/snakemake/issues/618/outdated-grammar-specification), therefore, these new words cannot be easily picked up from there.

**Comment by alerque** [comment]
It looks like `script` got added as part of 9f86547d.

I'll add `conda` now. Are there more since then? It looks like the grammar EBNF has not been updated...
